# Generated by Django 3.2 on 2021-05-13 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0005_alter_cereal_image'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_cereal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cereal.cereal'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/en/0/00/The_Child_aka_Baby_Yoda_%28Star_Wars%29.jpg', max_length=99999),
        ),
    ]
