# Generated by Django 3.2 on 2021-05-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://miro.medium.com/max/2400/1*mk1-6aYaf_Bes1E3Imhc0A.jpeg', upload_to='account/profile_pics'),
        ),
    ]
