INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (1, 'Can add log entry', 1, 'add_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (2, 'Can change log entry', 1, 'change_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (3, 'Can delete log entry', 1, 'delete_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (4, 'Can view log entry', 1, 'view_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (5, 'Can add permission', 2, 'add_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (6, 'Can change permission', 2, 'change_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (7, 'Can delete permission', 2, 'delete_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (8, 'Can view permission', 2, 'view_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (9, 'Can add group', 3, 'add_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (10, 'Can change group', 3, 'change_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (11, 'Can delete group', 3, 'delete_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (12, 'Can view group', 3, 'view_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (13, 'Can add user', 4, 'add_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (14, 'Can change user', 4, 'change_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (15, 'Can delete user', 4, 'delete_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (16, 'Can view user', 4, 'view_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (17, 'Can add content type', 5, 'add_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (18, 'Can change content type', 5, 'change_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (19, 'Can delete content type', 5, 'delete_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (20, 'Can view content type', 5, 'view_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (21, 'Can add session', 6, 'add_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (22, 'Can change session', 6, 'change_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (23, 'Can delete session', 6, 'delete_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (24, 'Can view session', 6, 'view_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (25, 'Can add cereal', 7, 'add_cereal');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (26, 'Can change cereal', 7, 'change_cereal');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (27, 'Can delete cereal', 7, 'delete_cereal');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (28, 'Can view cereal', 7, 'view_cereal');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (29, 'Can add create account', 8, 'add_createaccount');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (30, 'Can change create account', 8, 'change_createaccount');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (31, 'Can delete create account', 8, 'delete_createaccount');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (32, 'Can view create account', 8, 'view_createaccount');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (33, 'Can add create account image', 9, 'add_createaccountimage');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (34, 'Can change create account image', 9, 'change_createaccountimage');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (35, 'Can delete create account image', 9, 'delete_createaccountimage');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (36, 'Can view create account image', 9, 'view_createaccountimage');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (37, 'Can add user and password', 10, 'add_userandpassword');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (38, 'Can change user and password', 10, 'change_userandpassword');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (39, 'Can delete user and password', 10, 'delete_userandpassword');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (40, 'Can view user and password', 10, 'view_userandpassword');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (41, 'Can add create type', 11, 'add_createtype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (42, 'Can change create type', 11, 'change_createtype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (43, 'Can delete create type', 11, 'delete_createtype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (44, 'Can view create type', 11, 'view_createtype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (45, 'Can add create cereal', 12, 'add_createcereal');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (46, 'Can change create cereal', 12, 'change_createcereal');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (47, 'Can delete create cereal', 12, 'delete_createcereal');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (48, 'Can view create cereal', 12, 'view_createcereal');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (49, 'Can add cereal image', 13, 'add_cerealimage');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (50, 'Can change cereal image', 13, 'change_cerealimage');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (51, 'Can delete cereal image', 13, 'delete_cerealimage');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (52, 'Can view cereal image', 13, 'view_cerealimage');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (53, 'Can add manufacturer', 14, 'add_manufacturer');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (54, 'Can change manufacturer', 14, 'change_manufacturer');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (55, 'Can delete manufacturer', 14, 'delete_manufacturer');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (56, 'Can view manufacturer', 14, 'view_manufacturer');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (57, 'Can add nutrition value', 15, 'add_nutritionvalue');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (58, 'Can change nutrition value', 15, 'change_nutritionvalue');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (59, 'Can delete nutrition value', 15, 'delete_nutritionvalue');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (60, 'Can view nutrition value', 15, 'view_nutritionvalue');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (61, 'Can add type', 16, 'add_type');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (62, 'Can change type', 16, 'change_type');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (63, 'Can delete type', 16, 'delete_type');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (64, 'Can view type', 16, 'view_type');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (65, 'Can add order cereal item', 17, 'add_ordercerealitem');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (66, 'Can change order cereal item', 17, 'change_ordercerealitem');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (67, 'Can delete order cereal item', 17, 'delete_ordercerealitem');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (68, 'Can view order cereal item', 17, 'view_ordercerealitem');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (69, 'Can add order', 18, 'add_order');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (70, 'Can change order', 18, 'change_order');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (71, 'Can delete order', 18, 'delete_order');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (72, 'Can view order', 18, 'view_order');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (73, 'Can add profile', 19, 'add_profile');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (74, 'Can change profile', 19, 'change_profile');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (75, 'Can delete profile', 19, 'delete_profile');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (76, 'Can view profile', 19, 'view_profile');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (77, 'Can add user cart', 20, 'add_usercart');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (78, 'Can change user cart', 20, 'change_usercart');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (79, 'Can delete user cart', 20, 'delete_usercart');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (80, 'Can view user cart', 20, 'view_usercart');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (81, 'Can add toys', 21, 'add_toys');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (82, 'Can change toys', 21, 'change_toys');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (83, 'Can delete toys', 21, 'delete_toys');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (84, 'Can view toys', 21, 'view_toys');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (85, 'Can add card info', 22, 'add_cardinfo');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (86, 'Can change card info', 22, 'change_cardinfo');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (87, 'Can delete card info', 22, 'delete_cardinfo');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (88, 'Can view card info', 22, 'view_cardinfo');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (89, 'Can add user info', 23, 'add_userinfo');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (90, 'Can change user info', 23, 'change_userinfo');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (91, 'Can delete user info', 23, 'delete_userinfo');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (92, 'Can view user info', 23, 'view_userinfo');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (93, 'Can add toy cart', 24, 'add_toycart');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (94, 'Can change toy cart', 24, 'change_toycart');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (95, 'Can delete toy cart', 24, 'delete_toycart');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (96, 'Can view toy cart', 24, 'view_toycart');