# Generated by Django 3.2 on 2021-05-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinfo',
            name='expirationsDate',
            field=models.CharField(max_length=255),
        ),
    ]
