# Generated by Django 3.2 on 2021-05-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_cardinfo_expirationsdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinfo',
            name='CVC',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='cardNumber',
            field=models.IntegerField(max_length=16),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='expirationsDate',
            field=models.CharField(max_length=11),
        ),
    ]
