# Generated by Django 3.2 on 2021-05-08 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='createType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='createCereal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cerealName', models.CharField(max_length=255)),
                ('cerealNutritionalValue', models.CharField(max_length=255)),
                ('cerealContents', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cereal.createtype')),
            ],
        ),
        migrations.CreateModel(
            name='cerealImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=9999)),
                ('cereal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cereal.createcereal')),
            ],
        ),
    ]
