# Generated by Django 3.2 on 2021-05-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcereal',
            name='image',
            field=models.CharField(max_length=9999, null=True),
        ),
        migrations.DeleteModel(
            name='cerealImage',
        ),
    ]
