# Generated by Django 3.2 on 2021-05-10 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0003_createcereal_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='cereal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cerealName', models.CharField(max_length=255)),
                ('cerealContents', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=999, null=True)),
                ('amountInStock', models.FloatField()),
                ('price', models.FloatField()),
                ('image', models.CharField(max_length=9999, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturerName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='nutritionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutritionValue', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='createCereal',
        ),
        migrations.DeleteModel(
            name='createType',
        ),
        migrations.AddField(
            model_name='cereal',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cereal.manufacturer'),
        ),
        migrations.AddField(
            model_name='cereal',
            name='nutritionValue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cereal.nutritionvalue'),
        ),
        migrations.AddField(
            model_name='cereal',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cereal.type'),
        ),
    ]
