# Generated by Django 3.2 on 2021-05-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0004_auto_20210510_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cereal',
            name='image',
            field=models.CharField(max_length=99999, null=True),
        ),
    ]
