# Generated by Django 3.2 on 2021-05-11 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sign_up', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createaccountimage',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='createaccountimage',
            name='image',
            field=models.CharField(max_length=99999, null=True),
        ),
    ]
