# Generated by Django 3.2 on 2021-05-12 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cereal', '0005_alter_cereal_image'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cereal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cereal.cereal')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
