# Generated by Django 3.2 on 2021-05-14 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cereal', '0005_alter_cereal_image'),
        ('cart', '0003_auto_20210513_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='toyCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('toy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cereal.cereal')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
