# Generated by Django 3.2 on 2021-05-14 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
        ('cart', '0004_toycart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toycart',
            name='toy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toys.toys'),
        ),
    ]
