# Generated by Django 3.2 on 2021-05-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_toycart_toy'),
    ]

    operations = [
        migrations.AddField(
            model_name='toycart',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercart',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
