# Generated by Django 3.2 on 2021-05-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20210514_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toycart',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
